# Generated by Django 4.2.5 on 2024-01-14 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentario',
            old_name='aprovador',
            new_name='aprovado',
        ),
    ]
