# Generated by Django 4.2.5 on 2024-01-14 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('endereco', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='endereco',
            old_name='longetude',
            new_name='longitude',
        ),
    ]
