# Generated by Django 5.0.1 on 2024-01-12 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atracoes', '0001_initial'),
        ('pontos_turisticos', '0002_alter_pontosturisicos_aprovado'),
    ]

    operations = [
        migrations.AddField(
            model_name='pontosturisicos',
            name='atracoes',
            field=models.ManyToManyField(to='atracoes.atracao'),
        ),
    ]
