# Generated by Django 4.2.5 on 2024-01-13 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0001_initial'),
        ('pontos_turisticos', '0003_pontosturisicos_atracoes'),
    ]

    operations = [
        migrations.AddField(
            model_name='pontosturisicos',
            name='comentarios',
            field=models.ManyToManyField(to='comentarios.comentario'),
        ),
    ]
