# Generated by Django 4.2.5 on 2024-01-13 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacoes', '0001_initial'),
        ('pontos_turisticos', '0004_pontosturisicos_comentarios'),
    ]

    operations = [
        migrations.AddField(
            model_name='pontosturisicos',
            name='avaliacoes',
            field=models.ManyToManyField(to='avaliacoes.avaliacao'),
        ),
    ]
