# Generated by Django 4.2.5 on 2024-01-13 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('endereco', '0001_initial'),
        ('pontos_turisticos', '0006_pontosturisicos_endereco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pontosturisicos',
            name='endereco',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='endereco.endereco'),
        ),
    ]
