# Generated by Django 4.2.5 on 2024-01-14 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('endereco', '0002_rename_longetude_endereco_longitude'),
        ('avaliacoes', '0001_initial'),
        ('comentarios', '0001_initial'),
        ('atracoes', '0001_initial'),
        ('pontos_turisticos', '0007_alter_pontosturisicos_endereco'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PontosTurisicos',
            new_name='PontoTurisico',
        ),
    ]
