# Generated by Django 4.2.5 on 2024-01-14 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pontos_turisticos', '0008_rename_pontosturisicos_pontoturisico'),
    ]

    operations = [
        migrations.AddField(
            model_name='pontoturisico',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='pontos_turisticos'),
        ),
    ]
